//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.EcommerceManager.UserControls.DashBoard {
    
    
    public partial class CtrlAdminDashBoard {
        
        /// <summary>
        /// CtrlAdminRecentActivity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.EcommerceManager.UserControls.DashBoard.CtrlAdminRecentActivity CtrlAdminRecentActivity;
    }
}
