//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    
    public partial class OrderInfoList
    {
        public long OrderId { get; set; }
        public long ProductId { get; set; }
        public long CustomerId { get; set; }
        public int PaymentMethodId { get; set; }
        public int Quantity { get; set; }
        public decimal PriceAtOrderTime { get; set; }
        public int SalesAtOrderTime { get; set; }
        public int SalesTaxAtOrderTime { get; set; }
        public int PurchasedPrice { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<bool> OrderConfirmation { get; set; }
        public Nullable<System.DateTime> OrderConfirmationDate { get; set; }
        public Nullable<int> OrderConfirmBy { get; set; }
        public byte OrderStatus { get; set; }
        public Nullable<int> OrderStatusUpdateBy { get; set; }
        public Nullable<System.DateTime> OrderStatusUpdateDate { get; set; }
        public int StoreID { get; set; }
        public string TransactionId { get; set; }
        public Nullable<int> RefStoreId { get; set; }
    }
}
