//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    
    public partial class OrderStatusCustomer
    {
        public Nullable<long> RowNum { get; set; }
        public long OrderId { get; set; }
        public long ProductId { get; set; }
        public long CustomerId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<bool> OrderConfirmation { get; set; }
        public Nullable<System.DateTime> OrderConfirmationDate { get; set; }
        public byte OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderStatusUpdateDate { get; set; }
        public string OrderSite { get; set; }
        public Nullable<int> SalesAtOrderTime { get; set; }
        public Nullable<int> SalesTaxAtOrderTime { get; set; }
        public decimal PriceAtOrderTime { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public int ProductStatus { get; set; }
        public int ProductSale { get; set; }
        public int SalesTaxId { get; set; }
        public string ProductImage { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public string PaymentMethod { get; set; }
    }
}
