//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    
    public partial class ProductToCategories
    {
        public int PCCatId { get; set; }
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public string CatHierarchy { get; set; }
        public string CatName { get; set; }
        public long PCId { get; set; }
    }
}
