//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    
    public partial class ProductDynamicCategories
    {
        public string ProductName { get; set; }
        public long ProductID { get; set; }
        public string PDCValue { get; set; }
        public long PDAId { get; set; }
        public long PDCId { get; set; }
        public string PCDName { get; set; }
        public int StoreId { get; set; }
    }
}
