//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    
    public partial class SP_GetSubmittedtOrders_Result1
    {
        public long OrderId { get; set; }
        public long ProductId { get; set; }
        public long CustomerId { get; set; }
        public int PaymentMethodId { get; set; }
        public int Quantity { get; set; }
        public decimal PriceAtOrderTime { get; set; }
        public int SalesAtOrderTime { get; set; }
        public Nullable<int> SalesTaxAtOrderTime { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<bool> OrderConfirmation { get; set; }
        public Nullable<System.DateTime> OrderConfirmationDate { get; set; }
        public Nullable<int> OrderConfirmBy { get; set; }
        public byte OrderStatus { get; set; }
        public Nullable<int> OrderStatusUpdateBy { get; set; }
        public Nullable<System.DateTime> OrderStatusUpdateDate { get; set; }
        public int StoreID { get; set; }
        public string ProductName { get; set; }
        public long ProductInStock { get; set; }
        public Nullable<bool> ProductIsFeatured { get; set; }
        public int ProductStatus { get; set; }
        public int ProductSale { get; set; }
        public int SalesTaxId { get; set; }
        public int SalesTaxRate { get; set; }
        public string ProductImage { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string TelephoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string ProvinceOrState { get; set; }
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public byte Status { get; set; }
    }
}
