//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    
    public partial class StoreInformation
    {
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public string StoreOwnerName { get; set; }
        public string StoreOwnerContact { get; set; }
        public string StoreOwnerEmail { get; set; }
        public string StoreDomainName { get; set; }
        public int PackageId { get; set; }
        public string StoreLogo { get; set; }
        public bool StoreStatus { get; set; }
        public string StoreStatusComment { get; set; }
        public Nullable<int> StoreStatusUpdatedby { get; set; }
        public Nullable<System.DateTime> StoreStatusUpdatedDate { get; set; }
        public int BillingTermId { get; set; }
        public int CountryId { get; set; }
        public string StoreCity { get; set; }
        public string StorePostCode { get; set; }
        public string StoreContact { get; set; }
        public string SotreAddress { get; set; }
        public string TemplateName { get; set; }
    }
}
