//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HomePageBanners
    {
        public int HPBId { get; set; }
        public string BannerImage { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int StoreId { get; set; }
        public string Name { get; set; }
        public string LinkPath { get; set; }
        public int BannerOrder { get; set; }
    
        public virtual tbl_Stores tbl_Stores { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
