//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BillingTerm
    {
        public tbl_BillingTerm()
        {
            this.tbl_Stores = new HashSet<tbl_Stores>();
        }
    
        public int BTId { get; set; }
        public string BTTitle { get; set; }
        public decimal BTBill { get; set; }
        public int BTDuration { get; set; }
    
        public virtual ICollection<tbl_Stores> tbl_Stores { get; set; }
    }
}
