//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stores
    {
        public tbl_Stores()
        {
            this.tbl_Brands = new HashSet<tbl_Brands>();
            this.tbl_Categories = new HashSet<tbl_Categories>();
            this.tbl_Colors = new HashSet<tbl_Colors>();
            this.tbl_Customers = new HashSet<tbl_Customers>();
            this.tbl_GenderCategories = new HashSet<tbl_GenderCategories>();
            this.tbl_Groups = new HashSet<tbl_Groups>();
            this.tbl_HomePageBanners = new HashSet<tbl_HomePageBanners>();
            this.tbl_NextStorePaymentSchedule = new HashSet<tbl_NextStorePaymentSchedule>();
            this.tbl_NextStorePaymentSchedule1 = new HashSet<tbl_NextStorePaymentSchedule>();
            this.tbl_Orders = new HashSet<tbl_Orders>();
            this.tbl_Pages = new HashSet<tbl_Pages>();
            this.tbl_ProductDynamicCategories = new HashSet<tbl_ProductDynamicCategories>();
            this.tbl_SalesTaxRates = new HashSet<tbl_SalesTaxRates>();
            this.tbl_ScreensToGroup = new HashSet<tbl_ScreensToGroup>();
            this.tbl_StorePayment = new HashSet<tbl_StorePayment>();
            this.tbl_Users1 = new HashSet<tbl_Users>();
        }
    
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public string StoreOwnerName { get; set; }
        public string StoreOwnerContact { get; set; }
        public string StoreOwnerEmail { get; set; }
        public string StoreDomainName { get; set; }
        public int TemplateId { get; set; }
        public int PackageId { get; set; }
        public string StoreLogo { get; set; }
        public bool StoreStatus { get; set; }
        public string StoreStatusComment { get; set; }
        public Nullable<int> StoreStatusUpdatedby { get; set; }
        public Nullable<System.DateTime> StoreStatusUpdatedDate { get; set; }
        public int BillingTermId { get; set; }
        public int CountryId { get; set; }
        public string StoreCity { get; set; }
        public string StorePostCode { get; set; }
        public string StoreContact { get; set; }
        public string SotreAddress { get; set; }
    
        public virtual tbl_BillingTerm tbl_BillingTerm { get; set; }
        public virtual ICollection<tbl_Brands> tbl_Brands { get; set; }
        public virtual ICollection<tbl_Categories> tbl_Categories { get; set; }
        public virtual ICollection<tbl_Colors> tbl_Colors { get; set; }
        public virtual tbl_Country tbl_Country { get; set; }
        public virtual ICollection<tbl_Customers> tbl_Customers { get; set; }
        public virtual ICollection<tbl_GenderCategories> tbl_GenderCategories { get; set; }
        public virtual ICollection<tbl_Groups> tbl_Groups { get; set; }
        public virtual ICollection<tbl_HomePageBanners> tbl_HomePageBanners { get; set; }
        public virtual ICollection<tbl_NextStorePaymentSchedule> tbl_NextStorePaymentSchedule { get; set; }
        public virtual ICollection<tbl_NextStorePaymentSchedule> tbl_NextStorePaymentSchedule1 { get; set; }
        public virtual ICollection<tbl_Orders> tbl_Orders { get; set; }
        public virtual tbl_Packages tbl_Packages { get; set; }
        public virtual ICollection<tbl_Pages> tbl_Pages { get; set; }
        public virtual ICollection<tbl_ProductDynamicCategories> tbl_ProductDynamicCategories { get; set; }
        public virtual ICollection<tbl_SalesTaxRates> tbl_SalesTaxRates { get; set; }
        public virtual ICollection<tbl_ScreensToGroup> tbl_ScreensToGroup { get; set; }
        public virtual ICollection<tbl_StorePayment> tbl_StorePayment { get; set; }
        public virtual tbl_Templates tbl_Templates { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual ICollection<tbl_Users> tbl_Users1 { get; set; }
    }
}
