//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Colors
    {
        public tbl_Colors()
        {
            this.tbl_ProductsColors = new HashSet<tbl_ProductsColors>();
        }
    
        public int ColorId { get; set; }
        public string ColorName { get; set; }
        public string ColorCode { get; set; }
        public int StoreId { get; set; }
    
        public virtual tbl_Stores tbl_Stores { get; set; }
        public virtual ICollection<tbl_ProductsColors> tbl_ProductsColors { get; set; }
    }
}
