//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CategoriesUpdationRecord
    {
        public long CatUpdationRecord { get; set; }
        public int CatId { get; set; }
        public string CatName { get; set; }
        public string CatDescription { get; set; }
        public Nullable<long> CatParent { get; set; }
        public bool CatIsActive { get; set; }
        public System.DateTime CatModifiedDate { get; set; }
        public int CatModifiedBy { get; set; }
    
        public virtual tbl_Categories tbl_Categories { get; set; }
    }
}
