//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Packages
    {
        public tbl_Packages()
        {
            this.tbl_Stores = new HashSet<tbl_Stores>();
        }
    
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public Nullable<decimal> PackagePerMonthCost { get; set; }
        public Nullable<int> PackageTransactionPercentage { get; set; }
        public string Detail { get; set; }
    
        public virtual ICollection<tbl_Stores> tbl_Stores { get; set; }
    }
}
