//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductsColors
    {
        public long ProductColorId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<int> ColorId { get; set; }
    
        public virtual tbl_Colors tbl_Colors { get; set; }
        public virtual tbl_Products tbl_Products { get; set; }
    }
}
