//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Groups
    {
        public tbl_Groups()
        {
            this.tbl_ScreensToGroup = new HashSet<tbl_ScreensToGroup>();
            this.tbl_Users1 = new HashSet<tbl_Users>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
        public int GroupCreatedBy { get; set; }
        public System.DateTime GroupCreatedDate { get; set; }
        public int StoreId { get; set; }
        public bool Status { get; set; }
    
        public virtual tbl_Stores tbl_Stores { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual ICollection<tbl_ScreensToGroup> tbl_ScreensToGroup { get; set; }
        public virtual ICollection<tbl_Users> tbl_Users1 { get; set; }
    }
}
