//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BrandsUpdation
    {
        public int BrandUpdationId { get; set; }
        public int BrandId { get; set; }
        public string BrandDescription { get; set; }
        public int BrandsModifiedBy { get; set; }
        public System.DateTime BrandsModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string BrandName { get; set; }
        public string BrandImage { get; set; }
    
        public virtual tbl_Brands tbl_Brands { get; set; }
    }
}
