//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Products
    {
        public tbl_Products()
        {
            this.tbl_Orders = new HashSet<tbl_Orders>();
            this.tbl_ProductCategories = new HashSet<tbl_ProductCategories>();
            this.tbl_ProductDynamicAttributes = new HashSet<tbl_ProductDynamicAttributes>();
            this.tbl_ProductImages = new HashSet<tbl_ProductImages>();
            this.tbl_ProductMetarialInfo = new HashSet<tbl_ProductMetarialInfo>();
            this.tbl_ProductsColors = new HashSet<tbl_ProductsColors>();
            this.tbl_ProductsGender = new HashSet<tbl_ProductsGender>();
        }
    
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public int ProductBrandId { get; set; }
        public decimal ProductUnitPrice { get; set; }
        public string ProductPriceDescription { get; set; }
        public long ProductInStock { get; set; }
        public int ProductInsertedBy { get; set; }
        public System.DateTime ProductInsertedDate { get; set; }
        public int StoreId { get; set; }
        public Nullable<bool> ProductIsFeatured { get; set; }
        public int ProductStatus { get; set; }
        public int ProductSale { get; set; }
        public int SalesTaxId { get; set; }
        public string ProductImage { get; set; }
        public int PurchasePrice { get; set; }
    
        public virtual tbl_Brands tbl_Brands { get; set; }
        public virtual ICollection<tbl_Orders> tbl_Orders { get; set; }
        public virtual ICollection<tbl_ProductCategories> tbl_ProductCategories { get; set; }
        public virtual ICollection<tbl_ProductDynamicAttributes> tbl_ProductDynamicAttributes { get; set; }
        public virtual ICollection<tbl_ProductImages> tbl_ProductImages { get; set; }
        public virtual ICollection<tbl_ProductMetarialInfo> tbl_ProductMetarialInfo { get; set; }
        public virtual tbl_SalesTaxRates tbl_SalesTaxRates { get; set; }
        public virtual tbl_SalesTaxRates tbl_SalesTaxRates1 { get; set; }
        public virtual ICollection<tbl_ProductsColors> tbl_ProductsColors { get; set; }
        public virtual ICollection<tbl_ProductsGender> tbl_ProductsGender { get; set; }
    }
}
