//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Brands
    {
        public tbl_Brands()
        {
            this.tbl_BrandsUpdation = new HashSet<tbl_BrandsUpdation>();
            this.tbl_Products = new HashSet<tbl_Products>();
        }
    
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string BrandDescription { get; set; }
        public System.DateTime BrandUploadedDate { get; set; }
        public int BrandUploadedBy { get; set; }
        public Nullable<int> BrandLastUpdatedBy { get; set; }
        public Nullable<System.DateTime> BrandLastUpdatedDate { get; set; }
        public int StoreId { get; set; }
        public bool IsActive { get; set; }
        public string BrandImage { get; set; }
    
        public virtual tbl_Stores tbl_Stores { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_Users tbl_Users1 { get; set; }
        public virtual ICollection<tbl_BrandsUpdation> tbl_BrandsUpdation { get; set; }
        public virtual ICollection<tbl_Products> tbl_Products { get; set; }
    }
}
