//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Country
    {
        public tbl_Country()
        {
            this.tbl_Customers = new HashSet<tbl_Customers>();
            this.tbl_Stores = new HashSet<tbl_Stores>();
        }
    
        public int CountryId { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<tbl_Customers> tbl_Customers { get; set; }
        public virtual ICollection<tbl_Stores> tbl_Stores { get; set; }
    }
}
