//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        public tbl_Users()
        {
            this.tbl_Brands = new HashSet<tbl_Brands>();
            this.tbl_Brands1 = new HashSet<tbl_Brands>();
            this.tbl_Groups = new HashSet<tbl_Groups>();
            this.tbl_HomePageBanners = new HashSet<tbl_HomePageBanners>();
            this.tbl_NextStorePaymentSchedule = new HashSet<tbl_NextStorePaymentSchedule>();
            this.tbl_NextStorePaymentSchedule1 = new HashSet<tbl_NextStorePaymentSchedule>();
            this.tbl_Pages = new HashSet<tbl_Pages>();
            this.tbl_Pages1 = new HashSet<tbl_Pages>();
            this.tbl_PagesUpdation = new HashSet<tbl_PagesUpdation>();
            this.tbl_Stores = new HashSet<tbl_Stores>();
            this.tbl_Users1 = new HashSet<tbl_Users>();
            this.tbl_Users11 = new HashSet<tbl_Users>();
            this.tbl_UsersUpdation = new HashSet<tbl_UsersUpdation>();
        }
    
        public int UserId { get; set; }
        public string UserLoginId { get; set; }
        public string UserPwd { get; set; }
        public int StoreId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UserCreatedBy { get; set; }
        public System.DateTime UserCreatedDate { get; set; }
        public Nullable<int> UserLastModifiedBy { get; set; }
        public Nullable<System.DateTime> UserLastModifiedDate { get; set; }
        public string UserFullName { get; set; }
        public string UserIdentityInformation { get; set; }
        public string UserAddress { get; set; }
        public int UserGroupId { get; set; }
        public string UserEmail { get; set; }
    
        public virtual ICollection<tbl_Brands> tbl_Brands { get; set; }
        public virtual ICollection<tbl_Brands> tbl_Brands1 { get; set; }
        public virtual ICollection<tbl_Groups> tbl_Groups { get; set; }
        public virtual tbl_Groups tbl_Groups1 { get; set; }
        public virtual ICollection<tbl_HomePageBanners> tbl_HomePageBanners { get; set; }
        public virtual ICollection<tbl_NextStorePaymentSchedule> tbl_NextStorePaymentSchedule { get; set; }
        public virtual ICollection<tbl_NextStorePaymentSchedule> tbl_NextStorePaymentSchedule1 { get; set; }
        public virtual ICollection<tbl_Pages> tbl_Pages { get; set; }
        public virtual ICollection<tbl_Pages> tbl_Pages1 { get; set; }
        public virtual ICollection<tbl_PagesUpdation> tbl_PagesUpdation { get; set; }
        public virtual ICollection<tbl_Stores> tbl_Stores { get; set; }
        public virtual tbl_Stores tbl_Stores1 { get; set; }
        public virtual ICollection<tbl_Users> tbl_Users1 { get; set; }
        public virtual tbl_Users tbl_Users2 { get; set; }
        public virtual ICollection<tbl_Users> tbl_Users11 { get; set; }
        public virtual tbl_Users tbl_Users3 { get; set; }
        public virtual ICollection<tbl_UsersUpdation> tbl_UsersUpdation { get; set; }
    }
}
