//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StorePayment
    {
        public int StorePaymentId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<System.DateTime> StorePaymentFromDate { get; set; }
        public Nullable<System.DateTime> StorePaymentToDate { get; set; }
        public Nullable<decimal> StorePayment { get; set; }
        public Nullable<System.DateTime> StorePaymentDate { get; set; }
        public int StorePaymentInsertedBy { get; set; }
    
        public virtual tbl_Stores tbl_Stores { get; set; }
    }
}
