//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Pages
    {
        public tbl_Pages()
        {
            this.tbl_PagesUpdation = new HashSet<tbl_PagesUpdation>();
        }
    
        public int PageId { get; set; }
        public string PageName { get; set; }
        public string Meta { get; set; }
        public string Details { get; set; }
        public bool Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int StoreId { get; set; }
    
        public virtual tbl_Stores tbl_Stores { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_Users tbl_Users1 { get; set; }
        public virtual ICollection<tbl_PagesUpdation> tbl_PagesUpdation { get; set; }
    }
}
