//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductDynamicAttributes
    {
        public long PDAId { get; set; }
        public long ProductID { get; set; }
        public long PDCId { get; set; }
        public string PDCValue { get; set; }
    
        public virtual tbl_ProductDynamicCategories tbl_ProductDynamicCategories { get; set; }
        public virtual tbl_Products tbl_Products { get; set; }
    }
}
