//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductCategories
    {
        public long PCId { get; set; }
        public long PCProductId { get; set; }
        public int PCCatId { get; set; }
    
        public virtual tbl_Categories tbl_Categories { get; set; }
        public virtual tbl_Products tbl_Products { get; set; }
    }
}
