//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GenderCategories
    {
        public tbl_GenderCategories()
        {
            this.tbl_ProductsGender = new HashSet<tbl_ProductsGender>();
        }
    
        public int GenderCatId { get; set; }
        public string GenderCatName { get; set; }
        public string GenderCatDescription { get; set; }
        public int StoreId { get; set; }
    
        public virtual tbl_Stores tbl_Stores { get; set; }
        public virtual ICollection<tbl_ProductsGender> tbl_ProductsGender { get; set; }
    }
}
