//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentMethods
    {
        public tbl_PaymentMethods()
        {
            this.tbl_Orders = new HashSet<tbl_Orders>();
        }
    
        public int PaymentMethodId { get; set; }
        public string PaymentMethodName { get; set; }
        public string PaymentMethodDesc { get; set; }
    
        public virtual ICollection<tbl_Orders> tbl_Orders { get; set; }
    }
}
