//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Templates
    {
        public tbl_Templates()
        {
            this.tbl_Stores = new HashSet<tbl_Stores>();
        }
    
        public int TemplateId { get; set; }
        public string TemplateName { get; set; }
        public string TemplatePicture { get; set; }
        public int TemplateLogoWidth { get; set; }
        public int TemplateLogoHeight { get; set; }
    
        public virtual ICollection<tbl_Stores> tbl_Stores { get; set; }
    }
}
