//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UsersUpdation
    {
        public int UserUpdationId { get; set; }
        public int UserId { get; set; }
        public string UserPwd { get; set; }
        public bool IsActive { get; set; }
        public int UserLastModifiedBy { get; set; }
        public System.DateTime UserLastModifiedDate { get; set; }
        public string UserFullName { get; set; }
        public string UserIdentityInformation { get; set; }
        public string UserAddress { get; set; }
        public int UserGroupId { get; set; }
        public string UserEmail { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
