//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesTaxRatesUpdation
    {
        public long SalesTaxUpdationId { get; set; }
        public int SalesTaxId { get; set; }
        public int SalesTaxRate { get; set; }
        public string SalesTaxSector { get; set; }
        public int SalesTaxModifiedBy { get; set; }
        public System.DateTime SalesTaxLastUpdationDate { get; set; }
    
        public virtual tbl_SalesTaxRates tbl_SalesTaxRates { get; set; }
    }
}
