//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PagesUpdation
    {
        public int UpdationId { get; set; }
        public int PageId { get; set; }
        public string PageName { get; set; }
        public string Meta { get; set; }
        public string Details { get; set; }
        public bool Status { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual tbl_Pages tbl_Pages { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
