//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Categories
    {
        public tbl_Categories()
        {
            this.tbl_Categories1 = new HashSet<tbl_Categories>();
            this.tbl_CategoriesUpdationRecord = new HashSet<tbl_CategoriesUpdationRecord>();
            this.tbl_ProductCategories = new HashSet<tbl_ProductCategories>();
        }
    
        public int CatId { get; set; }
        public string CatName { get; set; }
        public string CatDescription { get; set; }
        public Nullable<int> CatParent { get; set; }
        public bool CatIsActive { get; set; }
        public int CatCreatedBy { get; set; }
        public System.DateTime CatCreatedDate { get; set; }
        public Nullable<int> CatLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CatLastModifiedDate { get; set; }
        public int StoreId { get; set; }
        public Nullable<long> ShowOrder { get; set; }
    
        public virtual ICollection<tbl_Categories> tbl_Categories1 { get; set; }
        public virtual tbl_Categories tbl_Categories2 { get; set; }
        public virtual tbl_Stores tbl_Stores { get; set; }
        public virtual ICollection<tbl_CategoriesUpdationRecord> tbl_CategoriesUpdationRecord { get; set; }
        public virtual ICollection<tbl_ProductCategories> tbl_ProductCategories { get; set; }
    }
}
