//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    
    public partial class Users
    {
        public int UserId { get; set; }
        public string UserLoginId { get; set; }
        public string UserPwd { get; set; }
        public int StoreId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UserCreatedBy { get; set; }
        public System.DateTime UserCreatedDate { get; set; }
        public Nullable<int> UserLastModifiedBy { get; set; }
        public Nullable<System.DateTime> UserLastModifiedDate { get; set; }
        public string UserFullName { get; set; }
        public string UserIdentityInformation { get; set; }
        public string UserAddress { get; set; }
        public int UserGroupId { get; set; }
        public string UserEmail { get; set; }
    }
}
