//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDAL
{
    using System;
    
    public partial class UsersInfo
    {
        public int UserId { get; set; }
        public string UserFullName { get; set; }
        public string UserLoginId { get; set; }
        public bool IsActive { get; set; }
        public int UserGroupId { get; set; }
        public string GroupName { get; set; }
        public bool GroupStatus { get; set; }
    }
}
