//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.MasterPages.Electronix {
    
    
    public partial class Index {
        
        /// <summary>
        /// HeadContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// CtrlTopSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.MasterPages.Electronix.UserControls.CtrlTopSearch CtrlTopSearch;
        
        /// <summary>
        /// CtrlHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.MasterPages.Electronix.UserControls.CtrlHeader CtrlHeader;
        
        /// <summary>
        /// CtrlMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.MasterPages.Electronix.CtrlMenu CtrlMenu;
        
        /// <summary>
        /// CtrlNavigation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.MasterPages.Electronix.UserControls.CtrlNavigation CtrlNavigation;
        
        /// <summary>
        /// CtrlCategories control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.MasterPages.Electronix.UserControls.CtrlCategories CtrlCategories;
        
        /// <summary>
        /// CtrlSpecialProduct control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.MasterPages.Electronix.UserControls.CtrlSpecialProduct CtrlSpecialProduct;
        
        /// <summary>
        /// CtrlNewsLetter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.MasterPages.Electronix.UserControls.CtrlNewsLetter CtrlNewsLetter;
        
        /// <summary>
        /// Contents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder Contents;
        
        /// <summary>
        /// CtrlShoppingCart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.MasterPages.Electronix.UserControls.CtrlShoppingCart CtrlShoppingCart;
        
        /// <summary>
        /// CtrlWhatsNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.MasterPages.Electronix.UserControls.CtrlWhatsNew CtrlWhatsNew;
        
        /// <summary>
        /// CtrlManufacturers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.MasterPages.Electronix.UserControls.CtrlManufacturers CtrlManufacturers;
        
        /// <summary>
        /// CtrlFooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.MasterPages.Electronix.UserControls.CtrlFooter CtrlFooter;
    }
}
