//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.EcommerceManager {
    
    
    public partial class ProductView {
        
        /// <summary>
        /// CtrlProductsView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.EcommerceManager.UserControls.Products.CtrlProductsView CtrlProductsView1;
        
        /// <summary>
        /// CtrlProductCategoriesView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.EcommerceManager.UserControls.Products.CtrlProductCategoriesView CtrlProductCategoriesView;
        
        /// <summary>
        /// CtrlProductColorGenderView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.EcommerceManager.UserControls.Products.CtrlProductColorGenderView CtrlProductColorGenderView1;
        
        /// <summary>
        /// CtrlProductDynamicPropertiesView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.EcommerceManager.UserControls.Products.CtrlProductDynamicPropertiesView CtrlProductDynamicPropertiesView1;
        
        /// <summary>
        /// CtrlProductImagesView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ecommerce.EcommerceManager.UserControls.Products.CtrlProductImagesView CtrlProductImagesView1;
    }
}
